import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/Navbar"
import { ActiveProvider } from '../components/context/activeContext';
import {Toaster} from 'react-hot-toast'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Falleh Bledi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ActiveProvider>
          <Navbar />
          <Toaster
  containerStyle={{
    top:50 ,
    left:500,
  }}
/>
          {children}
        </ActiveProvider>
      </body>
    </html>
  );
}